### ISSUE TITLE
Client-side "delayed" onground flag uses an invalid server-side cvar

### ISSUE THREAD

**Issue by MarioSMB** [KillPixelGames/wrath-darkplaces#3]
In V_CalcRefdefUsing, the "delayed" onground flag code checks sv_gameplayfix_nogravityonground.integer, which is defined on the server side.  
The correct check here would be `(cl.moveflags & MOVEFLAG_NOGRAVITYONGROUND)`

**Comment by fgsfdsfgs** [comment]
Thanks, missed that one.
