### ISSUE TITLE
Q: Regarding other darkplaces games

### ISSUE THREAD

**Issue by VortexAcherontic** [KillPixelGames/wrath-darkplaces#5]
Hello there, it's me again :smile: 

This is only a question regrading other games which do run with the "vanilla" version of the darkplaces engine such as Quake and it's mission packs. Since this is a port to fit your game I'd like to ask if compatibility to those are ensured or not.

I ran quake 1 (`warth-darkplaces-sdl -quake`) using it and didn't proceed further as to the main menu and at launching a single player game the engine crashes with this message:

````
Introduction
Host_Error: server attempted to read an invalid field in an edict (626248138)
QuakeC crash report for server:
s7380: STATE      MOVETYPE_TOSS (=6), player_run (=player_run())
s7381: ADDRESS    self (=entity 1), weaponframe (=.weaponframe), GLOBAL4859
s7382: STOREP_F   FALSE (=0), GLOBAL4859
````

If you do not plan for compatibility (which I assume since I wouldn't do so either :smile: ) I'd like to add this to the openSUSE package description so others may not flood this issue board with "Quake is not working" or "Xonotic is not running" eg. :smile: 

Kind regards,
Vortex

**Comment by fgsfdsfgs** [comment]
Compatibility with Quake's stock progs.dat is not preserved, but if you altered and recompiled the progs to include some changes (like the increased amount of params), then it will work. Same goes for most other games Darkplaces supports.
So in short the answer is no. That may change later though, if for example we only enable all the WRATH-related changes when the game mode is WRATH.

**Comment by VortexAcherontic** [comment]
Alright thank you for your answer :)

Since the question is answered I'll close this issue here.
